name: create a win package
on:
  push:
    branches: [ "kuri65536-patch-1" ]
  pull_request:
    branches: [ "kuri65536-patch-1" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      id:   msys2
      with:
        update:  true
        msystem: mingw64
        install: |
          mingw-w64-x86_64-libmupdf mingw-w64-libjpeg-turbo
          mingw-w64-harfbuzz mingw-w64-freetype mingw-w64-jbig2dec
          mingw-w64-x86_64-gumbo-parser mingw-w64-x86_64-mujs
    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version:  2.0.4 # optional, default is stable
    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.nimble
          ${{ steps.msys2.outputs.msys2-location }}
        key:  ${{ runner.os }}-${{ hashFiles('.nimble/bin/nim') }}
    - name: install dependencies
      run:  nimble install -d
    - run:  nim c --cincludes=${{env.bin1}}/include --clibdir=${{env.bin1}}/lib src/pdf_toc_bookmarks.nim 
      env:
        bin1: ${{ steps.msys2.outputs.msys2-location }}/mingw64
